server:
  port: 8080

#  主数据库定义（Primary）
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://rr-2ze05x4beb1axm8kdo.mysql.rds.aliyuncs.com:3306/biz_dl?serverTimezone=UTC"
    username: "myadmin"
    password: "mypassword"
    hikari:
      maximum-pool-size: 20 #连接池同一时间可分配的最大活跃连接数，默认是10

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8